# Mercedes-Benz Greener Manufacturing

## Objective - Reduce the time a Mercedes-Benz spends on the test bench.

### Key Tasks to be performed:
1. If for any column(s), the variance is equal to zero, then you need to remove those variable(s).<br>
2. Check for null and unique values for test and train sets.<br>
3. Apply label encoder.<br>
4. Perform dimensionality reduction.<br>
5. Predict your test_df values using XGBoost.<br>

In [4]:
## List of libraries to import
import numpy as np
import pandas as pd
from sklearn import model_selection
from numpy import absolute
from sklearn.model_selection import RepeatedKFold
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import LabelEncoder
import xgboost as XGB
import warnings
warnings.filterwarnings('ignore')
from sklearn.decomposition import PCA

In [5]:
Train_Data_Mercedes_Benz = pd.read_csv("C:/Working Files/Mac ka folder/Simplilearn/Machine Learning/Projects - Mercedes-Benz Greener Manufacturing/train.csv")
Test_Data_Mercedes_Benz = pd.read_csv("C:/Working Files/Mac ka folder/Simplilearn/Machine Learning/Projects - Mercedes-Benz Greener Manufacturing/test.csv")

In [6]:
Train_Data_Mercedes_Benz.columns

Index(['ID', 'y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=378)

In [10]:
Train_Data_Mercedes_Benz.head(2)

ID       y X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81  k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53  k  t  av  e  d  y  l  o  ...     1     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  

[2 rows x 378 columns]

In [11]:
Test_Data_Mercedes_Benz.columns

Index(['ID', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=377)

In [12]:
Test_Data_Mercedes_Benz.head(2)

ID  X0 X1  X2 X3 X4 X5 X6 X8  X10  ...  X375  X376  X377  X378  X379  X380  \
0   1  az  v   n  f  d  t  a  w    0  ...     0     0     0     1     0     0   
1   2   t  b  ai  a  d  b  g  y    0  ...     0     0     1     0     0     0   

   X382  X383  X384  X385  
0     0     0     0     0  
1     0     0     0     0  

[2 rows x 377 columns]

### Task1. If for any column(s), the variance is equal to zero, then you need to remove those variable(s).

In [13]:
Duplicated = []
for i in Train_Data_Mercedes_Benz.columns:
    if Train_Data_Mercedes_Benz[i].nunique() == 1:
        Duplicated.append(i)

In [16]:
Duplicated

['X11',
 'X93',
 'X107',
 'X233',
 'X235',
 'X268',
 'X289',
 'X290',
 'X293',
 'X297',
 'X330',
 'X347']

In [17]:
Train_Data_Mercedes_Benz.drop(Duplicated,axis=1,inplace=True)
Test_Data_Mercedes_Benz.drop(Duplicated,axis=1,inplace=True)

In [18]:
Train_Data_Mercedes_Benz.shape

(4209, 366)

In [19]:
Test_Data_Mercedes_Benz.shape

(4209, 365)

<span style='color:Red'> Duplicated Columns has been removed, Basically columns are symmetrical and variance is zero </span> <br>

### Task2. Check for null and unique values for test and train sets.
### Task3. Apply label encoder.

In [20]:
Train_Data_Mercedes_Benz.isnull().sum().sum()

0

In [21]:
Test_Data_Mercedes_Benz.isnull().sum().sum()

0

In [22]:
Train_Data_Mercedes_Benz.dtypes.value_counts()

int64      357
object       8
float64      1
dtype: int64

In [23]:
Train_Data_Mercedes_Benz.select_dtypes("object").columns

Index(['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'], dtype='object')

In [24]:
Train_Data_Mercedes_Benz[['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']]

X0 X1  X2 X3 X4  X5 X6 X8
0      k  v  at  a  d   u  j  o
1      k  t  av  e  d   y  l  o
2     az  w   n  c  d   x  j  x
3     az  t   n  f  d   x  l  e
4     az  v   n  f  d   h  d  n
...   .. ..  .. .. ..  .. .. ..
4204  ak  s  as  c  d  aa  d  q
4205   j  o   t  d  d  aa  h  h
4206  ak  v   r  a  d  aa  g  e
4207  al  r   e  f  d  aa  l  u
4208   z  r  ae  c  d  aa  g  w

[4209 rows x 8 columns]

In [25]:
encoder = LabelEncoder()

In [26]:
Train_Data_Mercedes_Benz['X0'] = encoder.fit_transform(Train_Data_Mercedes_Benz['X0'])
Train_Data_Mercedes_Benz['X1'] = encoder.fit_transform(Train_Data_Mercedes_Benz['X1'])
Train_Data_Mercedes_Benz['X2'] = encoder.fit_transform(Train_Data_Mercedes_Benz['X2'])
Train_Data_Mercedes_Benz['X3'] = encoder.fit_transform(Train_Data_Mercedes_Benz['X3'])
Train_Data_Mercedes_Benz['X4'] = encoder.fit_transform(Train_Data_Mercedes_Benz['X4'])
Train_Data_Mercedes_Benz['X5'] = encoder.fit_transform(Train_Data_Mercedes_Benz['X5'])
Train_Data_Mercedes_Benz['X6'] = encoder.fit_transform(Train_Data_Mercedes_Benz['X6'])
Train_Data_Mercedes_Benz['X8'] = encoder.fit_transform(Train_Data_Mercedes_Benz['X8'])

In [27]:
Train_Data_Mercedes_Benz[['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']]

X0  X1  X2  X3  X4  X5  X6  X8
0     32  23  17   0   3  24   9  14
1     32  21  19   4   3  28  11  14
2     20  24  34   2   3  27   9  23
3     20  21  34   5   3  27  11   4
4     20  23  34   5   3  12   3  13
...   ..  ..  ..  ..  ..  ..  ..  ..
4204   8  20  16   2   3   0   3  16
4205  31  16  40   3   3   0   7   7
4206   8  23  38   0   3   0   6   4
4207   9  19  25   5   3   0  11  20
4208  46  19   3   2   3   0   6  22

[4209 rows x 8 columns]

In [28]:
Test_Data_Mercedes_Benz[['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']]

X0  X1  X2 X3 X4  X5 X6 X8
0     az   v   n  f  d   t  a  w
1      t   b  ai  a  d   b  g  y
2     az   v  as  f  d   a  j  j
3     az   l   n  f  d   z  l  n
4      w   s  as  c  d   y  i  m
...   ..  ..  .. .. ..  .. .. ..
4204  aj   h  as  f  d  aa  j  e
4205   t  aa  ai  d  d  aa  j  y
4206   y   v  as  f  d  aa  d  w
4207  ak   v  as  a  d  aa  c  q
4208   t  aa  ai  c  d  aa  g  r

[4209 rows x 8 columns]

In [29]:
Test_Data_Mercedes_Benz['X0'] = encoder.fit_transform(Test_Data_Mercedes_Benz['X0'])
Test_Data_Mercedes_Benz['X1'] = encoder.fit_transform(Test_Data_Mercedes_Benz['X1'])
Test_Data_Mercedes_Benz['X2'] = encoder.fit_transform(Test_Data_Mercedes_Benz['X2'])
Test_Data_Mercedes_Benz['X3'] = encoder.fit_transform(Test_Data_Mercedes_Benz['X3'])
Test_Data_Mercedes_Benz['X4'] = encoder.fit_transform(Test_Data_Mercedes_Benz['X4'])
Test_Data_Mercedes_Benz['X5'] = encoder.fit_transform(Test_Data_Mercedes_Benz['X5'])
Test_Data_Mercedes_Benz['X6'] = encoder.fit_transform(Test_Data_Mercedes_Benz['X6'])
Test_Data_Mercedes_Benz['X8'] = encoder.fit_transform(Test_Data_Mercedes_Benz['X8'])

In [30]:
Test_Data_Mercedes_Benz[['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8']]

X0  X1  X2  X3  X4  X5  X6  X8
0     21  23  34   5   3  26   0  22
1     42   3   8   0   3   9   6  24
2     21  23  17   5   3   0   9   9
3     21  13  34   5   3  31  11  13
4     45  20  17   2   3  30   8  12
...   ..  ..  ..  ..  ..  ..  ..  ..
4204   6   9  17   5   3   1   9   4
4205  42   1   8   3   3   1   9  24
4206  47  23  17   5   3   1   3  22
4207   7  23  17   0   3   1   2  16
4208  42   1   8   2   3   1   6  17

[4209 rows x 8 columns]

In [31]:
Y_train = Train_Data_Mercedes_Benz["y"]
X_train = Train_Data_Mercedes_Benz.drop(["y","ID"],axis=1)
X_test = Test_Data_Mercedes_Benz.drop(["ID"],axis=1)

<span style='color:Red'> Columns ['X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8'] were categorical and we used label encoder to convert them in numeric   </span> <br>

### Task4. Perform dimensionality reduction.

In [32]:
sklearn_pca = PCA(n_components = 2)

In [33]:
sklearn_pca.fit(X_train)
X_train_transformed = sklearn_pca.transform(X_train)

print(X_train.shape)
print(X_train_transformed.shape)

(4209, 364)
(4209, 2)


In [34]:
X_test_transformed = sklearn_pca.transform(X_test)
print(X_test.shape)
print(X_test_transformed.shape)

(4209, 364)
(4209, 2)


In [48]:
sklearn_pca.explained_variance_ratio_*100

array([38.33478209, 21.38803259, 13.2618659 , 11.82664248,  9.20600842])

<span style='color:Blue'> Only 60% data coverd by 2 components, we need to increase the component count  </span> <br>

In [45]:
sklearn_pca = PCA(n_components = 5)

In [46]:
sklearn_pca.fit(X_train)
X_train_transformed = sklearn_pca.transform(X_train)

print(X_train.shape)
print(X_train_transformed.shape)

(4209, 364)
(4209, 5)


In [47]:
X_test_transformed = sklearn_pca.transform(X_test)
print(X_test.shape)
print(X_test_transformed.shape)

(4209, 364)
(4209, 5)


In [43]:
sklearn_pca.explained_variance_ratio_*100

array([38.33478209, 21.38803259, 13.2618659 , 11.82664248])

<span style='color:Red'> More than 90% data covered by components and we will use this for model building </span> <br>

### Task5. Predict your test_df values using XGBoost.

In [49]:
XGBR = XGB.XGBRegressor(n_estimators=100, reg_lambda=1, gamma=0, max_depth=3)

<span style='color:Blue'> Using Regressor as Y is continous variable  </span> <br>

In [50]:
XGBR.fit(X_test_transformed,Y_train)

XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=1,
             colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.300000012, max_delta_step=0, max_depth=3,
             min_child_weight=1, missing=nan, monotone_constraints='()',
             n_estimators=100, n_jobs=8, num_parallel_tree=1, random_state=0,
             reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [51]:
XGBR.feature_importances_

array([0.16005035, 0.24261843, 0.19697729, 0.20720884, 0.19314514],
      dtype=float32)

<span style='color:Blue'> All components are close to equally distributed based coefficients, all have equal importance </span> <br>

#### Evaluate the model using Cross Validation Score

In [53]:
cv = RepeatedKFold(n_splits=10, n_repeats=3, random_state=1)

In [59]:
scores = cross_val_score(XGBR, X_test_transformed, Y_train, scoring='neg_mean_absolute_error', cv=cv, n_jobs=-1)

In [58]:
scores = absolute(scores)
print(scores)

[10.55084684 10.30630629  9.92498347 10.57510678 10.14024551 10.61281122
 10.17017174 10.59589405 10.57073179 10.24617569  9.87958712 10.78277368
 10.62056716  9.73864338 10.38538591 10.04589126 10.85979055 10.217758
 10.46851003 10.11826783 10.49244267 10.53580403 10.15555517  9.94588413
 10.84106153 10.01838378 10.46881602 10.28192914 10.65438566 10.01311912]


<span style='color:Red'> mean_absolute_error close 10 for 10*3 Folds, model prediction is stable. </span> <br>

In [57]:
print('Mean MAE: %.2f (%.2f)' % (scores.mean(), scores.std()))

Mean MAE: 10.34 (0.30)
